#ifndef COMMON_H
#define COMMON_H
#include <unordered_set>
#include "llvm/Module.h"
#include "llvm/Pass.h"
#include "llvm/Function.h"
#include "llvm/Instructions.h"
#include "llvm/GlobalValue.h"
#include "llvm/Constants.h"
#include "llvm/Type.h"
#include "llvm/User.h"
#include "llvm/Attributes.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/ADT/SCCIterator.h"
//#include "llvm/DataLayout.h"
#include "llvm/Support/Debug.h"
#include "/home/jun/llvm-3.0.src/lib/VMCore/ConstantsContext.h"
#include <map>
#include <deque>
#include <fstream>
#include <sstream>
#include <stdio.h>
#include <stdlib.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <fcntl.h>
#include <unistd.h>
#include <iostream>
#include <list>
#include <queue>
#include <stack>
#include <set>
#include <string>
#include <syscall.h>
#include <sys/wait.h>
#endif
